### PR TITLE
Feature/update

### PR DESCRIPTION
**Pull request by Regenhardt**
Basically the first commit is only updating the library to netstandard21 and the examples to core3. 

The second commit applies some code style recommended by VS, i.e. using the new using declaration. I can remove this if you like, this just kinda happened.

### CODE REVIEW

**Comment by Regenhardt** [comment]
Sorry had an unnecessary change in the csproj, cleaned it up.

**Comment by ArcticEcho** [comment]
All the lines of code that now have discard assignments have been changed to use spaces instead of 
 tabs for indentation, which isn't really an issue in VS, but it kind of looks bad everywhere else.

I'll do a full review on monday. Thanks for the PR though! :)

**Comment by Regenhardt** [comment]
Ok give me a second. Glad you saw that, as I usually prefer tabs too. Must be the new install having other standard settings.

**Comment by Regenhardt** [comment]
So configuring my fresh install indeed helped.
It's possible I overshot a bit this time - I completely tabified the files I touched. How about keeping them tabified an also adding an editorconfig to the repo that automatically sets tabs as standard? Helps against this kind of thing😅.

**Comment by Regenhardt** [comment]
I'd put just the essentials in the editorconfig for now - tabs, size 4, encoding utf8.

**Comment by Regenhardt** [comment]
Since I'm updating anyway: Should I also update nuget dependencies and the assembly/nuget version? Would do that in another commit.

**Comment by ArcticEcho** [comment]
Yeah, may as well update that too.

**Comment by Regenhardt** [comment]
I updated the major version, since this is a breaking change to people not on netstandard21/core3. had to make some adjustments, since AngleSharp changed some namespaces and API names.

**Comment by Regenhardt** [comment]
Man I would prefer having some automatic tests now, since I don't have an actually working bot yet 😅.

**Comment by ArcticEcho** [comment]
Yeah, automated testing was something I wanted to add as well. However, most functions require authentication to work; and failing to see a clean way of handling that, I just left it. :D

The sample code is really the only thing I can point you towards wrt your broken bot. As I mentioned before, feel free to open an issue if you need help.

Anyway, the PR looks fine. Thanks for your contribution!

**Pull request merged**
